### ISSUE TITLE
Use dynamic fieldnames to reduce repetition

### ISSUE THREAD

**Issue by DrPaulSharp** [RascalSoftware/RAT#119]
In many places in the code, such as `parseClassToStruct.m` and `packParams.m` we loop over the set of fields in a struct, performing the same operation on each.

Where reasonable to implement, we should make use of the `fieldnames` function, and dynamic fieldnames: https://uk.mathworks.com/help/matlab/matlab_prog/generate-field-names-from-variables.html to reduce the repeated code that must be modified as the fields are changed.

**Comment by arwelHughes** [comment]
Speed though is the main consideration always - especially when compiled. Packparams is used gazillions of times during optimisations, so any slowdown, however slight, we should reject even if it makes the code neater.
A

________________________________
From: Paul Sharp ***@***.***>
Sent: Tuesday, April 18, 2023 4:53 PM
To: RascalSoftware/RAT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RascalSoftware/RAT] Use dynamic fieldnames to reduce repetition (Issue #119)


In many places in the code, such as parseClassToStruct.m and packParams.m we loop over the set of fields in a struct, performing the same operation on each.

Where reasonable to implement, we should make use of the fieldnames function, and dynamic fieldnames: https://uk.mathworks.com/help/matlab/matlab_prog/generate-field-names-from-variables.html to reduce the repeated code that must be modified as the fields are changed.

**Comment by DrPaulSharp** [comment]
Very good point. @StephenNneji do you know of a profiler we could use for matlab coder compiled code? Might be worth thinking about a reasonably substantial (~1 min) benchmark calculation as well.

**Comment by arwelHughes** [comment]
Hi All,
Mathworks already provide this….

See here https://uk.mathworks.com/help/coder/ug/profile-generated-mex-functions-using-matlab-profiler.html

Cheers,
Arwel


From: Paul Sharp ***@***.***>
Date: Tuesday, 18 April 2023 at 20:23
To: RascalSoftware/RAT ***@***.***>
Cc: Hughes, Arwel (STFC,RAL,ISIS) ***@***.***>, Comment ***@***.***>
Subject: Re: [RascalSoftware/RAT] Use dynamic fieldnames to reduce repetition (Issue #119)

Very good point. @StephenNneji<https://github.com/StephenNneji> do you know of a profiler we could use for matlab coder compiled code? Might be worth thinking about a reasonably substantial (~1 min) benchmark calculation as well.
