### ISSUE TITLE
Propagate exception of unknown mex to a warning for the user...

### ISSUE THREAD

**Issue by arwelHughes** [RascalSoftware/RAT#140]
In reflectivityCalculationWrapper, if the mex is not available we catch and throw an exception....

```
try
       [problem,result] = reflectivityCalculation_mex(problemDef,problemDefCells,problemDefLimits,controls);
    catch exception
        if (strcmp(exception.identifier, 'MATLAB:UndefinedFunction'))
            [problem,result] = reflectivityCalculation(problemDef,problemDefCells,problemDefLimits,controls);
        else
            rethrow(exception)
        end
    end
```

But, the user might not be aware of this, and would just carry on using the code, but with a much reduced performance.

Can we propagate this exception, so that if it's thrown, a warning is printed to the user? 

This shouldn't be at every iteration, but at the end of the run, so in the printout of RAT itself (or RATmain) might be a good place. e.g. somewhere around here??

```
if ~strcmpi(controls.display,'off')
   sendTextOutput(sprintf('\nFinished RAT ______________________________________________________________________________________________ \n\n'));
end

if the exception
 warning('RAT is using the Matlab version of the calculation, which will signigicantly degrade performance..... etc etc
```

Something like this?
A

**Comment by StephenNneji** [comment]
I don't understand what you mean by every iteration? 

> This shouldn't be at every iteration, but at the end of the run, so in the printout of RAT itself (or RATmain) might be a good place. e.g. somewhere around here??

**Comment by arwelHughes** [comment]
Ah, by 'iteration' I mean every time the reflectivity calculation is called.  So, for example, a simple Simplex minimisation will involve >1e6 calls to reflectivityCalculationWrapper, so that would be a million identical warning messages is it was printed from there! (this would almost certainly crash Matlab, or hang it for a long time at the very least....)

**Comment by DrPaulSharp** [comment]
Closing issue as this routine has been removed from the code in #161.
