### ISSUE TITLE
Implement copy functionality for projectClass?

### ISSUE THREAD

**Issue by arwelHughes** [RascalSoftware/RAT#180]
I've noticed that trying to copy projectClass makes a new reference to the existing object, rather than a copy of it. This is the default behaviour for handle classes, but can be overridden..

https://uk.mathworks.com/help/matlab/matlab_oop/custom-copy-behavior.html

It would be useful to implement a copy method for projectClass()

**Comment by DrPaulSharp** [comment]
Whilst the implementation above does enable a handle class to be copied, it only allows for a shallow copy - i.e., references in the object are copied, and hence point to the same object. This means that for projectClass, we can make a copy of the object, and changing (say) the experiment name behaves as expected:

![image](https://github.com/RascalSoftware/RAT/assets/44529197/cb3b6812-bac9-4da6-bb94-6ccd1bb0a4d7)

but when adding a layer, the reference for both p and q is to the same layersClass object, so we have the following.

![image](https://github.com/RascalSoftware/RAT/assets/44529197/f4296c96-8855-4cfe-ab05-31ed953945e1)

Matlab does not seem to have the capacity to make deep copies that would resolve this issue: https://uk.mathworks.com/matlabcentral/answers/41674-deep-copy-of-handle-object
