### ISSUE TITLE
Renaming variable causes tests to fail

### ISSUE THREAD

**Issue by DrPaulSharp** [RascalSoftware/RAT#181]
When renaming "nbs" as "bulkOut" in "targetFunctions/+nonPolarisedTF/*/processCustomFunctions.m", the tests fail with the error: 

"Index exceeds the number of array elements. Index must not exceed 1." in `backSort.m`.

Is there a reason why the input and output to `backSort.m` must be named differently - I not the output has been named as "bulkOut" historically, unlike the rest of the `targetFunctions` code.

**Comment by arwelHughes** [comment]
Which line number? Have you tried running the Matlab version with breakpoints?

**Comment by StephenNneji** [comment]
The problem is that when the nba is renamed to bulkOut, the value now changes in the for loop leading to the index error in subsequent iterations
```
for i = 1:numberOfContrasts     % TODO - the ambition is for parfor here, but would fail for Matlab and Python CM's..
         ...
         [~,~,~,bulkIn,bulkOut,~] = backSort(..., bulkIn,bulkOut,res);
         ...
    end
```
 The solution is to change variable names of the outputs from backsort

**Comment by DrPaulSharp** [comment]
Ahh, of course. I think a bit of code blindness set in there. I'll tidy that up shortly then.

Cheers,
Paul


Dr Paul Sharp

Senior Software Scientist

ISIS Neutron and Muon Source

STFC Rutherford Appleton Laboratory

Harwell, Oxford

OX11 0QX

[cid:7699df67-7354-4c5e-81b4-83be4ad76997]

________________________________

**Comment by arwelHughes** [comment]
Also, bulkIn going into backsort is an array, whereas in backsort a single value is chose (cNba's etc are arrays of indexes). So, the array / single value definition will have been made upstream somewhere....

**Comment by DrPaulSharp** [comment]
Yeah, that's where I thought the problem might have been, and hence what I was worried about.
