### ISSUE TITLE
Convert result cell array to struct

### ISSUE THREAD

**Issue by StephenNneji** [RascalSoftware/RAT#188]
The result cell array from `RATMain` should be converted to a struct with appropriate labels maybe 

- reflectivity
- simulation
- shiftedData
- layersSlds
- sldProfiles
- resampledLayers

`[~,~,results,~] = RATMain_mex(problemDef,problemDefCells,problemDefLimits,controls,priors);`

**Comment by DrPaulSharp** [comment]
Isn't this done in `parseResultToStruct`?

**Comment by DrPaulSharp** [comment]
Closed by #207

**Comment by DrPaulSharp** [comment]
Closed by https://github.com/RascalSoftware/RAT/pull/207
