### ISSUE TITLE
BayesResults needs refactoring

### ISSUE THREAD

**Issue by StephenNneji** [RascalSoftware/RAT#190]
Bayes result is exposed to the user so it need to be properly documented.
Variable name like `Dreampars.N` need to be changed to more meaningful ones
Any data not useful to the user should be removed from the struct

**Comment by arwelHughes** [comment]
"Bayes result is exposed to the user so it need to be properly documented"
Everything still needs to be properly documented.

"Variable name like Dreampars.N need to be changed to more meaningful one"
Variable names are as described in Vrugt et al.. https://www.sciencedirect.com/science/article/abs/pii/S1364815215300396
They need to stay as they are to avoid confusion.

"Any data not useful to the user should be removed from the struct"
It has been...
________________________________
From: StephenNneji ***@***.***>
Sent: Thursday, January 11, 2024 12:39 PM
To: RascalSoftware/RAT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RascalSoftware/RAT] BayesResults needs refactoring (Issue #190)


Bayes result is exposed to the user so it need to be properly documented.
Variable name like Dreampars.N need to be changed to more meaningful ones
Any data not useful to the user should be removed from the struct

**Comment by StephenNneji** [comment]
@arwelHughes BayesResult does not only contain the Dreampars, it also contains nestOutput, Predlims, BestFitsMean, ParConfInts etc. Are these also related to a paper?

**Comment by arwelHughes** [comment]
Ah yes - nest output should be removed in it's entirety for a DREAM run, and dreamOutput should be removed entirely for NS - my apologies. They both have to be present coming back from the compiled though because I think Coder requires a fully defined struct for input / output at compile time(?), and so we need to cull them in RAT.m , which should probably happen in mergeStructs.m ?

Predlims, BestFitsMean, ParConfInts are the whole point of doing the analysis though - those are the real results the users are looking for. We could think of better acronyms, but 'parConfInts' stands for 'Parameter Confidence Intervals', which is too long. Predlims stands for "Prediction intervals and limits"....  you have to shorten them to something or it just gets silly! 🙂   I've tried to keep them vaguely meaningful by just camel-casing shortened versions of what they are, but there's scope to change them I guess.
A


________________________________

**Comment by DrPaulSharp** [comment]
I'm taking a look at this now. As has been stated, we require a consistently defined struct throughout the compiled code. I also agree that the variable names leave something to be desired, and should be improved. Looking at the DREAMPar sub struct, presumerably these variables correspond to inputs defined elsewhere? That should mean we already have some better names on hand.

In particular, I'm keen on flattening the struct as there are a number of substructs that I'm not convinced are helpful. I think the starting point should be to remove the intermediate "bayesRes" struct entirely, leaving its contents "allChains", "nestOutput" and "dreamOutput" as part of the main "bayesResults" struct. I'm somewhat confused by the "Meas_info" struct in "dreamOutput" - what does this struct do and is it necessary? Could it be replaced with a simpler variable that does the same job?

Let me know any other thoughts you have.

**Comment by arwelHughes** [comment]
Hi Paul,

As mentioned, all the DREAm stuff comes from Vrught , Environmental Modelling & Software 75 (2016) 273e316 , and the parameters / inputs are set to conform to that paper as much as possible. So, the parameter names all conform to this table…..

[A screenshot of a computer  Description automatically generated]

Also, the paper gives a lot of examples as to how to use DREAM, eg like this……
[A screenshot of a computer  Description automatically generated]
So, we set up everything to conform to the paper. If we change everything, I know what will happen – we’ll just get a lot of questions from confused users (probably)!

So whatever looks strange, blame the paper! 😊
A






From: Paul Sharp ***@***.***>
Date: Friday, 1 March 2024 at 15:11
To: RascalSoftware/RAT ***@***.***>
Cc: Hughes, Arwel (STFC,RAL,ISIS) ***@***.***>, Mention ***@***.***>
Subject: Re: [RascalSoftware/RAT] BayesResults needs refactoring (Issue #190)

I'm taking a look at this now. As has been stated, we require a consistently defined struct throughout the compiled code. I also agree that the variable names leave something to be desired, and should be improved. Looking at the DREAMPar sub struct, presumerably these variables correspond to inputs defined elsewhere? That should mean we already have some better names on hand.

In particular, I'm keen on flattening the struct as there are a number of substructs that I'm not convinced are helpful. I think the starting point should be to remove the intermediate "bayesRes" struct entirely, leaving its contents "allChains", "nestOutput" and "dreamOutput" as part of the main "bayesResults" struct. I'm somewhat confused by the "Meas_info" struct in "dreamOutput" - what does this struct do and is it necessary? Could it be replaced with a simpler variable that does the same job?

Let me know any other thoughts you have.

**Comment by DrPaulSharp** [comment]
I've made the following changes to the `bayesResults` struct so far:

1) Renamed `bestPars` to `bestParams` - I intend to make similar changes whenever they show up elsewhere.

2) Renamed `bestFitsMean` to `bestFitMean` and `bestFitMean.ref` to `bestFitMean.reflectivity`

3) Renamed `predlims` to `predictionIntervals` with fields `reflectivity`, `sld`, `reflectivityXData`, `sldXData`, `sampleChi`

4) Renamed `parConfInts` to `confidenceIntervals` with fields `percentile95`, `percentile65`, `mean`

5) Renamed `nestOutput` as `nestedSamplerOutput`

6) Removed `Meas_info` from `dreamOutput`

7) Moved `bayesResults.dreamOutput.DREAMPar` to `bayesResults.dreamParams`

8) Renamed `dreamOutput.RunTime` to `dreamOutput.runtime`

9) Renamed `dreamParams.lambda` to `dreamParams.jumpProbability`

I think we can go further, but let me know what you make of things so far: https://github.com/DrPaulSharp/RAT/tree/bayes
I would emphasise that we can easily make changes to what the user sees in their output without affecting the internals of the minimisers. I think one good example would be to change `dreamParams.N` to `dreamParams.nChains`, which matches the controls class.

In addition, I have a couple of questions:

1) In the example I have, `results.bestFitPars` is identical to `bayesResults.bestParams`. Is this always the case? If so wqe should remove `bayesResults.bestParams` from the output.

2) Is `allChains` only used by dream as seems to be the case? If so I suggest it is moved into `dreamOutput`.

**Comment by DrPaulSharp** [comment]
Closed by #212
