### ISSUE TITLE
Number of parameters in "problem" struct does not match input or output

### ISSUE THREAD

**Issue by DrPaulSharp** [RascalSoftware/RAT#193]
When running a calculation in RAT, RATMain outputs a struct called "problem" containing fields including: backgroundParams, qzshifts, scalefactors, bulkIn, bulkOut, resolutionParams. However, the number of values included in these fields does not match up with the number of values in in input or output problemDef/problemStruct.

For example, when running the example "controlAlgorithms" we find:

Input

backgroundParams [2.28525214157571e-06, 3.10246417982706e-06]
qzshifts [0.0]
scalefactors [0.102860901766649, 0.151378164199993]
bulkIn [2.07399989449186e-06]
bulkOut [5.98067802097389e-06, 2.21e-06]
resolutionParams [0.03]

Problem

backgroundParams [2.28525214e-06, 3.10246418e-06]
qzshifts [0., 0.]
scalefactors [0.1028609, 0.1028609]
bulkIn [2.07399989e-06, 2.07399989e-06]
bulkOut [5.98067802e-06, 2.21000000e-06]
resolutionParams [0.03, 0.03]

Output

backgroundParams [2.28525214e-06, 3.10246418e-06]
qzshifts [0.]
scalefactors [0.1028609,  0.15137816]
bulkIn [2.07399989e-06]
bulkOut [5.98067802e-06 2.21000000e-06]
resolutionParams [0.03]

**Comment by arwelHughes** [comment]
In this project, there are two contrasts. The parameters get shared between the contrasts according to how they are picked up when the contrasts are defined. 

e.g., in this project....
Input:
There is one value of bulk-in defined in projectClass = one value of bulk in input.

Problem:
Each contrast uses the same value of bulk in = [*same* bulk in value repeated twice, one for each contrast]

Output:
There is one fitted value of bulk in = one value of bulk in for output.

Generally:- Input / output = number of values for a param as defined in projectClass
                             Problem = number of values equals number of contrasts.

A

**Comment by DrPaulSharp** [comment]
Ahh, I see - with the other key here being that two scalefactors are defined, but both contrasts use the first scalefactor defined.

Good, panic over.
