### ISSUE TITLE
Can we set contrast model in a loop?

### ISSUE THREAD

**Issue by arwelHughes** [RascalSoftware/RAT#197]
From the examples, I do this....

problem.setContrastModel(1,'DSPC Model');
problem.setContrastModel(2,'DSPC Model');
problem.setContrastModel(3,'DSPC Model');

It would be quite nice to ba able to go...

problem.setContrastModel(1:3,'DSPC Model');

..and just a simple loop (if it's a vector input). Can we do this??
A

**Comment by StephenNneji** [comment]
Update setContrastModel method accept a array of indices to set 

`problem.setContrastModel(1:3,  'DSPC Model');`
