### ISSUE TITLE
Still problems with specifying custom files...

### ISSUE THREAD

**Issue by arwelHughes** [RascalSoftware/RAT#238]
We are still finding problems with setting custom file names. 
For example, examples/normalReflectivity/customLayersDSPCSheet.mlx no longer runs on my machine:

<img width="1018" alt="Screenshot 2024-06-20 at 12 12 22" src="https://github.com/RascalSoftware/RAT/assets/26794718/1318f891-b772-4b5a-bda6-99a34adef52a">

**Comment by arwelHughes** [comment]
tbh I think we are checking too aggressively in 'toStruct', and it's fine just to let RAT handle exceptions at runtime?

**Comment by StephenNneji** [comment]
@arwelHughes While I would typically agree with you to let RAT handle exception, the checks just revealed a potential bug. I am guessing you intended to run _RAT\examples\normalReflectivity\customLayers\customBilayer.m_ but there is another file on path with the same name so potentially a user could have been running an incorrect function and never know or maybe complain that their changes are not reflecting in RAT. So I think these checks are good to avoid confusion. 

Also the Matlab live script will not find "customBilayer.m" even if the file is in the current directory as it seems the live script does not run in the current directory. 

So I will rename the files in the tests directory to hopefully avoid conflicts then see if I can update the live scripts to do a addpath so the files can be found
