### ISSUE TITLE
Clean up compile folder

### ISSUE THREAD

**Issue by StephenNneji** [RascalSoftware/RAT#68]
Remove unnecessary build artifacts, test files and any other file autogenerated by the build

The following folders will be removed:

1. **simplex**
2. **DE**
3. **Dram_compile**
4. **RAT_main_compile**

**Comment by StephenNneji** [comment]
@arwelHughes please let me know if any folders above should not be deleted

**Comment by arwelHughes** [comment]
Please remove......
