### ISSUE TITLE
Modifications to multiTypeTable have broken 'examples' ('setBackgroundValue')

### ISSUE THREAD

**Issue by arwelHughes** [RascalSoftware/RAT#82]
e.g. when running /examples/custom layers an error is thrown when trying to point value 1 of the 1st background to the renamed background value. 

Error using multiTypeTable.findRowIndex
Unrecognised parameter name

Error in multiTypeTable/setValue (line 113)
                col = obj.findRowIndex(colPar,colNames);

Error in backgroundsClass/setBackgroundValue (line 213)
            obj.backgrounds.setValue(in);

Error in projectClass/setBackgroundValue (line 458)
            obj.background.setBackgroundValue(varargin);

Error in orsoDSPC_custLay_script (line 102)
problem.setBackgroundValue(1,'value','Backs par D2O');

The problem also seems to affect the other examples (none of them now run)..

**Comment by StephenNneji** [comment]
This should be `problem.setBackgroundValue(1, 'value 1', 'Backs par D2O');` instead. I will go through and fix the examples
