### ISSUE TITLE
Investigate the use of namespaces to improve API structure

### ISSUE THREAD

**Issue by StephenNneji** [RascalSoftware/RAT#91]
MATLAB has a folder based implementation of namespaces [namespaces](https://www.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html). Can we use this to avoid names like `standardTF_custXY_paraContrasts` and have `standardTF.custXY.paraContrasts` instead?

**Comment by arwelHughes** [comment]
The reasons for the functions decision at the start was performance and compiling.

 Firstly, it used to be the case that there was a negative performance hit with classes as opposed to functions (this may not be the case now). But secondly, Matlab Coder mat not know about namespaces (and again a performance hit?).

In the engine, the overriding consideration is pure speed. In the API tho, that doesn't matter..... namespaces may be useful for different calculation types etc..

A
